### PR TITLE
add options for subscription cancellation

### PR DESCRIPTION
**Pull request by SaikumarChintada**
add cancel_at_cycle_end option for subscription cancellation api.

### CODE REVIEW

**Comment by SaikumarChintada** [comment]
api for undo cancellation  of subscription when cancel_at_cycle_end is enabled would also be helpful

**Comment by SaikumarChintada** [comment]
api call for undo subscription cancellation when cancel_at_cycle_end is enabled will be helpful. (api call must be made before the cycle ends)

**Comment by SaikumarChintada** [comment]
@msonowal  workaround for now,
**dependency**  https://github.com/rmccue/Requests
```
$url = 'https://api.razorpay.com/v1/subscriptions/'.$subscription_id.'/cancel';
$payload = ['cancel_at_cycle_end' => 1];
$headers = array('Accept' => 'application/json');
$options = array('auth' => array(self::$razorpaySecretId, self::$razorpaySecretKey));
$response = Requests::post($url, $headers,$payload, $options);
```

**Comment by msonowal** [comment]
@SaikumarChintada 
yes I am also doing it like that only for now

**Comment by harman28** [comment]
#83 was a duplicate of this, but got merged first.

Merging this anyway, because it was the first proposed PR to fix the options issue :)

**Pull request merged**
